apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitops-demo
resources:
- namespace.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
commonLabels:
  app.kubernetes.io/part-of: demo-app
  managed-by: argocd
