apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: gitops-demo
  labels:
    app: demo-app
spec:
  type: NodePort
  selector:
    app: demo-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
